# Site settings
title: "FIX, eCommerce on Heroku"
email: mars@heroku.com
description: > # this means to ignore newlines until "baseurl:"
  Example Salesforce-backed eCommerce system running on Heroku.
baseurl: "/fix" # the subpath of your site, e.g. /blog/
url: "https://heroku.github.io" # the base hostname & protocol for your site
twitter_username: heroku
github_username:  heroku
demo_url: https://fixcoffee.herokuapp.com
github_url: https://github.com/heroku/fix
installer_url: https://getyourfix.herokuapp.com

# Build settings
markdown: kramdown
exclude:
  - vendor
  - Gemfile
  - Gemfile.lock
  - README.markdown
